const emails = [
  { 
    name: 'new_account',
    subject: 'Welcome to Gravity',
    body: 'Thank you for signing up to Gravity. Your account is now verified.',
    button_label: 'Open Dashboard',
    button_url: '{{domain}}/dashboard',
    locale: 'en',
  },
  { 
    name: 'duplicate_user',
    subject: 'Important! Your Gravity account',
    body: 'We noticed you have already registered an account, so we used your original password to save you any confusion in the future.',
    button_label: 'Sign In',
    button_url: '{{domain}}/signin',
    locale: 'en',
  },
  { 
    name: 'new_plan',
    subject: 'Your Gravity plan',
    body: 'Thank you for selecting the {{content.plan}} plan. Your card has been successfully charged {{content.price}}.',
    button_label: 'Your Dashboard',
    button_url: '{{domain}}/dashboard',
    locale: 'en',
  },
  { 
    name: 'new_user',
    subject: 'Welcome to Gravity',
    body: 'Thank you for signing up to Gravity.',
    button_label: 'Open Dashboard',
    button_url: '{{domain}}/dashboard',
    locale: 'en',
  },
  { 
    name: 'plan_updated',
    subject: 'Your billing plan has been updated',
    body: 'This is confirmation that your billing plan has been successfully updated to the {{content.plan}} plan.',
    button_label: 'Manage Your Plan',
    button_url: '{{domain}}/account/billing',
    locale: 'en',
  },
  { 
    name: 'plan_updated_free',
    subject: 'Your billing plan has been downgraded',
    body: 'This is confirmation that your billing plan will be downgraded to free at the end of your current billing cycle.',
    button_label: 'Manage Your Plan',
    button_url: '{{domain}}/account/billing',
    locale: 'en',
  },
  { 
    name: 'card_updated',
    subject: 'Your credit card has been updated',
    body: 'This is confirmation that your credit card has been updated. If you didn\'t change your card, please let us know.',
    button_label: 'Contact Support',
    button_url: 'mailto:support@yourdomain.com',
    locale: 'en',
  },
  { 
    name: 'account_closed',
    subject: 'We\'re sorry to see you go',
    body: 'This is confirmation that your account has been closed and all of your data has been removed from our servers. \n If you change your mind, you can create a new account any time.',
    button_label: 'Sign Up',
    button_url: '{{domain}}/signup',
    locale: 'en',
  },
  { 
    name: 'invite_accepted',
    subject: 'Your friend accepted your invite',
    body: 'Woohoo! {{content.friend}} has accepted your invitation to join your team.',
    button_label: 'Invite More Users',
    button_url: '{{domain}}/account/users',
    locale: 'en',
  },
  { 
    name: 'password_updated',
    subject: 'Your password has been changed',
    body: 'Your new password has been saved. \n If you didn\'t change your password, please contact us and let us know.',
    button_label: 'Contact Support',
    button_url: 'mailto:support@yourdomain.com',
    locale: 'en',
  },
  { 
    name: 'password_reset',
    subject: 'You requested a password reset',
    body: 'Click the link below to reset your password.',
    button_label: 'Reset Password',
    button_url: '{{domain}}?token={{content.token}}',
    locale: 'en',
  },
  { 
    name: 'invite',
    subject: 'Your friend has invited you to use Gravity',
    body: 'Your friend {{content.friend}} has invited you to join his team on Gravity. Sign up now to start working with {{content.friend}}.',
    button_label: 'Sign Up Now',
    button_url: '{{domain}}?id={{content.id}}&email={{content.email}}',
    locale: 'en',
  },
  { 
    name: 'contact',
    subject: 'New message via contact form',
    body: '{{content.name}} has sent you a new message. \n\n {{content.message}}',
    button_label: 'Respond Now',
    button_url: 'mailto:{{content.email}}',
    locale: 'en',
  },
  { 
    name: 'feedback',
    subject: 'New feedback',
    body: 'You received a new piece of feedback \n\n Rating: {{content.rating}} \n\n{{content.comment}}',
    button_label: 'View Now',
    button_url: '{{domain}}/feedback',
    locale: 'en',
  },
  { 
    name: 'magic_signin',
    subject: 'Your magic sign in link',
    body: 'You requested a magic signin link for Gravity. Please click the link below to sign in without your password.',
    button_label: 'Sign In',
    button_url: '{{domain}}?token={{content.token}}',
    locale: 'en',
  },
  { 
    name: 'new_signin',
    subject: 'New sign in to Gravity',
    body: 'We noticed a new sign in to your account from a new device or location. <b>Was this you?</b>\n\n{{content.browser}} on {{content.device}}\n\n<b>IP</b>: {{content.ip}}\n\n<b>Time</b>: {{content.time}}\n\nIf this was you, you can ignore this message. If this wasn\'t you, please change your password.',
    button_label: 'Change Password',
    button_url: '{{domain}}/account/password',
    locale: 'en',
  },
  { 
    name: 'blocked_signin',
    subject: 'Suspicious sign in blocked',
    body: 'We noticed a suspicious sign in to your account and blocked it for security purposes. If this was you, you can sign in using the link below.',
    button_label: 'Sign In',
    button_url: '{{domain}}?token={{content.token}}',
    locale: 'en',
  },
  { 
    name: 'help',
    subject: 'New support message',
    body: '{{content.name}} has sent you a new message.\n\n {{content.message}}',
    button_label: 'Respond Now',
    button_url: 'mailto:{{content.email}}',
    locale: 'en',
  },
  { 
    name: 'new_log',
    subject: 'New log recorded in Gravity',
    body: 'A new log was made in your Gravity app, log in to Mission Control to see what happened.',
    button_label: 'View Log',
    button_url: '{{domain}}/logs/{{content.id}}',
    locale: 'en',
  },
  { 
    name: 'email_verification',
    subject: 'Please verify your email',
    body: 'Please click the link below to verify your email address.',
    button_label: 'Verify Your Email',
    button_url: '{{domain}}?token={{content.verification_token}}',
    locale: 'en',
  },
  { 
    name: 'trial_expiring',
    subject: 'Your trial will expire in 3 days',
    body: 'Your account will be automatically upgraded using the card details you provided.',
    button_label: 'Manage Your Account',
    button_url: '{{domain}}/account',
    locale: 'en',
  },
  { 
    name: 'trial_expired',
    subject: 'Your trial has ended',
    body: 'Your account has been automatically upgraded to the {{content.plan}} plan.',
    button_label: 'Open Dashboard',
    button_url: '{{domain}}/dashboard',
    locale: 'en',
  },
  { 
    name: 'unverified_account',
    subject: 'Reminder to verify your account',
    body: 'Please click the link below to verify your email address.',
    button_label: 'Verify Your Email',
    button_url: '{{domain}}/signup/verify?token={{content.verification_token}}',
    locale: 'en',
  },
]

module.exports = emails;